domain_path: C:\Users\sanat\FPGA_Car_Project\Vitis_Vid_Pass\vitis_vid_pass\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
